---
title: "About Me"
---

Thank you for visiting my site! I'm Rich Hanna, a data scientist with a background in biomedical and mechanical engineering currently developing software and data-driven solutions in pediatric medicine to support cutting-edge clinical research. This site is meant to serve as a portfolio of my work, a space for collaboration, and place for some of my own interests and hobbies.

## Professional Side

At the Children’s Hospital of Philadelphia, I am a member of the [Cell & Gene Therapy]( https://www.chop.edu/centers-programs/cell-and-gene-therapy-collaborative) Informatics team supporting the [Cellular Therapy and Transplant Section]( https://www.chop.edu/centers-programs/cellular-therapy-and-transplant-section), [Bone and Marrow Transplant Program]( https://www.chop.edu/centers-programs/blood-and-marrow-transplant-program), and various parts of the oncology and pathology divisions of the hospital. 

In the past I have also worked closely with the Critical Care Medicine and Emergency Medicine departments and spent considerable time in the development of data driven solutions for the [pediatric resuscitation quality collaborative](https://www.pedires-q.org/the-pedires-q-team), [National Emergency Airway Registry](https://www.ncbi.nlm.nih.gov/pubmed/23328260), and [Videography in Pediatric Emergency Resuscitation Collaborative]( https://medschool.cuanschutz.edu/pediatrics/sections/emergency-medicine/research-and-quality-improvement/the-videography-in-pediatric-emergency-resuscitation-(viper)-collaborative).

R is my premier language, but I enjoy learning wherever possible. I am very proud to be the developer of multiple `shiny` applications, a [CRAN certified R package](https://cran.r-project.org/web/packages/REDCapTidieR/index.html), and  a co-author on [multiple publications](https://www.richardshanna.com/publications.html) thanks my data science pursuits. I have also worked with Matlab, Python, SQL, and am [AWS Solutions Architect certified](https://www.credly.com/badges/44361ea8-9eb9-4f27-99ca-05b582f5b962?source=linked_in_profile).

## Unprofessional Side

Since I spend most waking hours in front of screens (who amongst us hasn't flipped from "work screen" directly over to "fun screen" a la video games), I spend much of my free time away from them. 

I'm an avid fake-it-till-you-make it runner because I'm very stubborn. Having flat feet and asthma should probably amount to a pretty terrible athlete, but I've been running ~5ks intermittently because on top of being stubborn I'm also spiteful. When possible, my wife and I like to take hikes, ride out bikes, and explore the world around us.

On the opposite end of the spectrum from fitness, I greatly enjoy cooking and baking. For some reason, working with my hands taps into the "engineering" side of what I like doing. After all, kitchen creations borderline alchemical in their design. I hope to add a lot to this site showcasing my creations!

I also enjoy drawing and photography, you may see some of those hobbies appear across this site as well!
